// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'only Android and Web are supported.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA__tMBGiQ-PVqyvv9kvNHaSUJk2QPXU-c',
    appId: '1:220656898723:web:42544ab4f0d20e4d20a516',
    messagingSenderId: '220656898723',
    projectId: 'wheeler-event-detection',
    authDomain: 'wheeler-event-detection.firebaseapp.com',
    databaseURL: 'https://wheeler-event-detection-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wheeler-event-detection.firebasestorage.app',
    measurementId: 'G-8DS2SYKYNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7KKwRFJc4ZovPTSqdFlTmnuNnapwu3o0',
    appId: '1:220656898723:android:caa95b50b2c1f7ca20a516',
    messagingSenderId: '220656898723',
    projectId: 'wheeler-event-detection',
    databaseURL: 'https://wheeler-event-detection-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'wheeler-event-detection.firebasestorage.app',
  );

}